SET SEARCH_PATH TO premiere;

ALTER TABLE "bank" ADD COLUMN "public_key" VARCHAR(500);

INSERT INTO "bank"(bank_name, public_key)
VALUES ('Taixiubank', 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEnQ7g/Fh8CkpuslkUDg7PbxzC\nHddDm6Z053ULOvFXRiYd06TnDeGERoQVrVltPmlhlZ6jz+Ltb4Tvf3C7LEK9h6TJ\nBfEmJISg/7fa6kOcLA/iT8SErhCQH7LH+asdG3XaPOd7V73vsLwdkm01S+KexNFe\nUo9t62h4OBVJVRXG6wIDAQAB');
